# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, set of tools, and commands
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      # Install system dependencies if needed
      - apt-get update
      - apt-get install -y --no-install-recommends git
    post_checkout:
      # Clone the main repository for API documentation
      - git clone --depth 1 https://github.com/geezacoleman/OpenWeedLocator.git _external/OpenWeedLocator

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: _external/OpenWeedLocator
      extra_requirements:
        - docs

# Set the version of Python and other tools you want to use
submodules:
  include: []
  exclude: all
