# .github/workflows/build-docs.yml
name: Build Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:
  # Trigger when main repo updates
  repository_dispatch:
    types: [main-repo-updated]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout documentation repo
      uses: actions/checkout@v4

    - name: Checkout main OWL repository
      uses: actions/checkout@v4
      with:
        repository: geezacoleman/OpenWeedLocator
        path: _external/OpenWeedLocator

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build documentation
      run: |
        cd docs
        sphinx-build -b html . _build/html -W --keep-going

    - name: Check for broken links
      run: |
        cd docs
        sphinx-build -b linkcheck . _build/linkcheck
      continue-on-error: true

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html/

    - name: Deploy to GitHub Pages (if main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/

  spell-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Spell check
      uses: streetsidesoftware/cspell-action@v5
      with:
        files: "docs/**/*.md"
        config: ".cspell.json"
        strict: false
